global:
  image:
    # repository: "quay.io/argoproj/argocd"
    # tag: "v2.8.10"
    # repository: "quay.io/akram/argocd"
    # tag: "sharding-with-default"
    repository: "docker.io/enclavet/argocd"
    tag: "unmarshall1"

dex:
  enabled: false # Disable dex since we are not using

controller:
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: true

repoServer:
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: true

applicationSet:
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: true

server:
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    type: "LoadBalancer"
