# Global configuration
global:
  gc: false

# Jobs configuration
jobs:
  # Job to create Namespaces, Roles, and RoleBindings
  - name: create-namespaces
    jobIterations: 100
    cleanup: false
    qps: 10  # Increased qps to handle more requests
    burst: 50 # Increased burst to allow higher initial throughput
    objects:
      - kind: Namespace
        objectTemplate: template/namespace.yaml
        replicas: 1
  - name: create-role
    jobIterations: 100
    cleanup: false
    qps: 10
    burst: 50
    objects:
      - kind: Role
        objectTemplate: template/role.yaml
        replicas: 1
  - name: create-rolebinding
    jobIterations: 100
    cleanup: false
    qps: 10
    burst: 50
    objects:
      - kind: RoleBinding
        objectTemplate: template/rolebinding.yaml
        replicas: 1            
  # Job to create ArgoCD applications
  - name: create-applications
    jobIterations: 100
    cleanup: false
    waitWhenFinished: true
    qps: 10
    burst: 50
    objects:
      - kind: Application
        objectTemplate: template/application.yaml
        replicas: 1
        waitOptions:
          forCondition: "Synced"
          customStatusPath: ".operationState.syncResult.resources[].status"
