apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-{{.Iteration}}
  namespace: <argocd-namespace>
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj-labs/argocd-performance-test
    targetRevision: HEAD
    path: tools/kube-burner/sample-test-resource
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-test-{{.Iteration}}
  syncPolicy:
    automated: {}
